# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 11:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('udemy_api', '0002_auto_20170506_0705'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usuario',
            table='usuario',
        ),
    ]
